USE [master]
GO

/****** Object:  Database [music_database]    Script Date: 14-04-2024 19:34:07 ******/
CREATE DATABASE [music_database]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'music_database', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\music_database.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'music_database_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\music_database_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [music_database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [music_database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [music_database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [music_database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [music_database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [music_database] SET ARITHABORT OFF 
GO

ALTER DATABASE [music_database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [music_database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [music_database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [music_database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [music_database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [music_database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [music_database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [music_database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [music_database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [music_database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [music_database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [music_database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [music_database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [music_database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [music_database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [music_database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [music_database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [music_database] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [music_database] SET  MULTI_USER 
GO

ALTER DATABASE [music_database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [music_database] SET DB_CHAINING OFF 
GO

ALTER DATABASE [music_database] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [music_database] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [music_database] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [music_database] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [music_database] SET QUERY_STORE = ON
GO

ALTER DATABASE [music_database] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [music_database] SET  READ_WRITE 
GO

